name: Testing matrix strategy

on:
  push:
    paths:
      - .github/workflows/matrix-strategy-test.yml
      
jobs:
  test:
   strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]
        include:
          - os: windows-latest
            node: 16
            npm: 10
        exclude:
          - os: windows-latest
            node: 20
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: action/setup-node@v4
       with:
         node-version: ${{ matrix.node }}
     - run: echo "npm test"
     - if: ${{matrix.npm}}
       run: echo "npm i -g npm@${{matrix.npm}}"
    