name: Testing matrix strategy

on:
  push:
    paths:
      - .github/workflows/matrix-strategy-test.yml
      
jobs:
  test:
   strategy:
      matrix:
        os: [os1, os2]
        node: [node1, node2]
        include:
          - os: os1
            node: node3
            npm: npm1
        exclude:
          - os: os2
            node: node1
   runs-on: ubuntu-latest
   steps:
     - run: echo ${{matrix.os}} + ${{matrix.node}}
     - if: ${{matrix.npm}}
       run: echo ${{matrix.os}} "+" ${{matrix.node}} "+" ${{matrix.npm}}
    