name: Secrets + Repository Environment Example

on:
  push:
    paths:
      - .github/workflows/repository-environment-test.yml

# Workflow-level env using environment secret
env:
  SECRET_1: ${{ secrets.SECRET_1 }}

jobs:
  demo:
    runs-on: ubuntu-latest

    # Attach repository environment
    # This environment must be created beforehand in you're github repository -> settings -> environments
    environment: testing

    # Job-level env using environment secrets
    env:
      SECRET_2: ${{ secrets.SECRET_2 }}
      SECRET_3: ${{ secrets.SECRET_3 }}

    steps:
      - uses: actions/checkout@v4

      - name: Use workflow + job level environment secrets
        run: |
          echo "SECRET_1 is available as: $SECRET_1 (masked)"
          echo "SECRET_1 length = ${#SECRET_1}"

          echo "SECRET_2 is available as: $SECRET_2 (masked)"
          echo "SECRET_2 length = ${#SECRET_2}"

          echo "SECRET_3 is available as: $SECRET_3 (masked)"
          echo "SECRET_3 length = ${#SECRET_3}"

      # Step-level env using environment secret
      - name: Step-level environment secret example
        env:
          SECRET_4: ${{ secrets.SECRET_4 }}
        run: |
          echo "SECRET_4 is available only in this step as: $SECRET_4 (masked)"
          echo "SECRET_4 length = ${#SECRET_4}"
